In [32]:
import numpy as np

In [64]:
a = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print a.shape
a.reshape(-1,2)

(2, 2, 3)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [11, 12],
       [13, 14],
       [15, 16]])

In [68]:
np.ceil([0.0005,0])

array([ 1.,  0.])

In [40]:
type([[1,2,3],[2,3,4]])

list

In [47]:
b = [1,2,3]
b+b

[1, 2, 3, 1, 2, 3]

In [55]:
np.abs(-1)

1

In [51]:
a -np.ones((2,3))

array([[ 0.,  1.,  2.],
       [ 1.,  2.,  3.]])

In [54]:
ls = [1,2,3]
print type(ls)
npls = np.array(np.array(ls))
print type(npls)

<type 'list'>
<type 'numpy.ndarray'>


## Numpy tips
### Avoid using rank 1 array

In [24]:
a = np.random.randn(5)
a

array([-1.75574601,  0.2559111 , -0.01701514, -0.86727417, -0.63573091])

In [25]:
# a is a rank 1 array, it is neight a row vector or a column vector
a.shape

(5,)

In [26]:
a.T

array([-1.75574601,  0.2559111 , -0.01701514, -0.86727417, -0.63573091])

In [27]:
np.dot(a, a.T)

4.3047423280200645

In [29]:
# use reshape to make the array a matrix
a.reshape(5,1)

array([[-1.75574601],
       [ 0.2559111 ],
       [-0.01701514],
       [-0.86727417],
       [-0.63573091]])

### Use (n,1) matrix instead

In [18]:
a = np.random.randn(5,1)
a

array([[-0.30982049],
       [-0.0175798 ],
       [ 0.97103687],
       [ 0.44093764],
       [ 0.17703902]])

In [19]:
a.T

array([[-0.30982049, -0.0175798 ,  0.97103687,  0.44093764,  0.17703902]])

In [20]:
np.dot(a, a.T)

array([[  9.59887351e-02,   5.44658138e-03,  -3.00847117e-01,
         -1.36611514e-01,  -5.48503143e-02],
       [  5.44658138e-03,   3.09049272e-04,  -1.70706313e-02,
         -7.75159426e-03,  -3.11231000e-03],
       [ -3.00847117e-01,  -1.70706313e-02,   9.42912603e-01,
          4.28166703e-01,   1.71911412e-01],
       [ -1.36611514e-01,  -7.75159426e-03,   4.28166703e-01,
          1.94426000e-01,   7.80631652e-02],
       [ -5.48503143e-02,  -3.11231000e-03,   1.71911412e-01,
          7.80631652e-02,   3.13428131e-02]])

### Use Assert to check a matrix's dimension

In [23]:
assert(a.shape == (5,1))